### ISSUE TITLE
HTML Loader by potatojam

### ISSUE THREAD

**Issue by astrochili** [astrochili/awesome-defold#3]
Due to lack of documentation, not sure what the purpose is. But it seems for sure some kind of HTML loader example is needed... is this it? 

- [HTML Loader](https://github.com/potatojam/defold-html-loader) — HTML Loader.

**Comment by astrochili** [comment]
@potatojam Hi! Could you please help sort this out?

**Comment by astrochili** [comment]
@sergeysinyavsky Hi! Could you please help sort this out?

**Comment by sergeysinyavsky** [comment]
@astrochili Hi! This extension adds a loading percentage and a spinning circle in the corner.
We use it in all our projects. I didn't complete it as an extension because I didn't make it flexible.
It may not work properly if you have some special template with your styles.
Looks like:
![image](https://github.com/astrochili/awesome-defold/assets/12486956/1a5ae892-fd72-45ce-b60a-6d8fbe48337f)

The circle will be hided when the game is loaded.
You can show it again and add text with percentages. We use this when load resources with liveupdate.

```
function init(self)
    if html_loader then
        html_loader.show()
        html_loader.set_text("Loading")

        self.percent = 0
        timer.delay(0.2, true, function(self, handle, time_elapsed)
            self.percent = self.percent + 1
            html_loader.set_progress(self.percent)
            if self.percent == 100 then
                timer.cancel(handle)
                html_loader.hide()
            end
        end)  
    end
end
```

**Comment by astrochili** [comment]
Thank you for such a detailed response! It turns out to be some kind of example that might be useful.

It also would be useful add this comment to yout README 🙏. Anyway would like to add a link to the list 👍
